### ISSUE TITLE
Why does CT slice change from single in ROI calculation?

### ISSUE THREAD

**Issue by idinsmore1** [MASILab/ALARM#1]
Hi there,

I was looking at your code in get_liver_measurement_JC2_V2.py, and am wondering why when you start calculating the peripheral ROI's, you are changing the slice number that you are interested in from your erosion calculation? Particularly this segment of code:
```
start=np.inf
for i in range(seg_iso.shape[0]):
    #figure out the edge of liver in this particular direction
    if(seg_iso[i][single[1]][single[-1]]==1):
        start=i
        break
#fetch the 1/3 point away from edge
midptr=(start+int((single[0]-start)/3),single[1],single[-1])
#mask
newmask=np.zeros(seg_iso.shape)
for i in range(15):
    for j in range(15):
        for k in range(5):
            #draw a circle around that point (based on distance)
            a,b,c=midptr[0]+7-i,midptr[1]+7-j,midptr[-1]+7-k
            if((a-midptr[0])**2+(b-midptr[1])**2<=7**2):
                newmask[a][b][c]=1 #marked 1
``` 

Why is the value of k changing when we had established that `single` contains the i, j, k of the center cut? Thanks for any insight!

**Comment by idinsmore1** [comment]
Or could it be that this is supposed to be `for k in range(15)`, not 5? That would make sense as then you are moving around the midpoint above and below the `single` i, j, k

**Comment by BennettLandman** [comment]
I am closing the older bug reports as these were missed. We are now better tracking reports across the organization. Please re-open if this continues to be a blocker.
